// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Belt_Option = require("bs-platform/lib/js/belt_Option.js");

var let_ = Belt_Option.flatMap;

exports.let_ = let_;
/* No side effect */
