// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var DoubleEndedQueue = require("double-ended-queue");

var dq = new DoubleEndedQueue([
      1,
      2,
      3,
      4
    ]);

console.log(dq);

console.log(dq.shift());

console.log(dq.pop());

dq.push(1);

console.log(dq);

exports.dq = dq;
/* dq Not a pure module */
